# Generated by Django 4.0.3 on 2022-03-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_rename_room_message_room_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_messages',
            new_name='room',
        ),
    ]
